### ISSUE TITLE
Role 'shared space permissions' does not save properly

### ISSUE THREAD

**Issue by alexkhudyshkin** [biblibre/urungi#197]
**Describe the bug**
Role settings in 'shared space permissions' tab don't save properly.

**To Reproduce**
1. Go to 'Roles'
2. Click on 'New Role'
3. Add a name for the role
4. Go to 'Shared space permissions' tab
5. Enable 'Execute reports'
6. Click 'Save'
7. Open role settings again, observe that 'Execute reports' is not enabled.

**Expected behavior**
Role should keep its settings after you press the 'Save' button.

**Comment by PaulPoulain** [comment]
@alexkhudyshkin , thanks for your bug report, don't hesitate to open more, we'll try to fix them. And if you have the skills to fix any, pull requests will be welcomed. Welcome onboard though.

PS: your picture is a monument from Moscow ? We have exactly the same in Paris !
PS2 : ;) kidding ;)

**Comment by alexkhudyshkin** [comment]
@PaulPoulain hello, let me introduce myself :)  I've been using widestage for quite a while now and I like it, but it has some issues, so I've been watching for your project for some time and hope you guys can make it really good!
Unfortunately javascript is too complicated for me, I prefer Python, although I haven't participated 
in big projects yet, just code for myself from time to time. But I can be useful in testing Urungi, especially for security issues (I'm an information security specialist) :)

P.S. I have been studying for 6 months in France and that's why the picture is here :)

**Comment by PaulPoulain** [comment]
I'm pretty sure you've seen the functional differences between Urungi and widestage, but if you have questions feel free to ask ! You may have noticed that Urungi & widestage dashboards are different, so it's no more possible to export a widestage mongoDB and import it in Urungi.
It is also actively supported, because we're deploying it for our customers (more than 200 libraries all around Europe and more).
Any contribution is warmly welcome, security bugs, functional testing, ... and if you want to submit a theme (new feature), I'd be happy to add it.
