### ISSUE TITLE
Browse PostgreSQL Schemas

### ISSUE THREAD

**Issue by tbenita** [biblibre/urungi#231]
Most of our applications run in PostgreSQL schemas. The ability to browse them would simplify the requests creation process.

When I browse the source database I can see all the tables but not those that are into a schema that is not default.

It would be nice to be able either to specify a schema in the database source description or to be able to browse schemas.

**Comment by jajm** [comment]
Hi @tbenita 

It would be a great future, but we use [knex](https://knexjs.org/) for building sql queries and it doesn't work very well with schemas:

> NOTE: identifier syntax has no place for selecting schema, so if you are doing schemaName.tableName, query might be rendered wrong. Use .withSchema('schemaName') instead.
> -- https://knexjs.org/#Builder-identifier-syntax

`.withSchema` works at the query level, so to work with multiple schemas we would have to use subqueries, which would make the code more complicated than it already is.
That's not the first problem we encounter with knex, so we might drop it in the future but that will not happen soon.

As a first step, we can probably make the schema configurable in the datasource, and use that instead of 'public'.
Another option is to make `search_path` configurable

**Comment by tbenita** [comment]
Hi @jajm ,
The configurable search_path would be great.
